---
name: deploy-terraform

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint
    # so that we can authenticate with AWS
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}

      - name: Validate Terraform config
        run: terraform validate
        shell: bash

      - name: Apply Terraform changes
        run: apply -auto-approve
        shell: bash
