---
name: deploy-terraform

on:
  push:
    branches: [main]

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint
    # so that we can authenticate with AWS
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          terraform-iam-role-arn: ${{ secrets.TERRAFORM_IAM_ROLE_ARN }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install sale.flag schema generation requirements
        run: pip install -r ./glue/schema/requirements.txt
        shell: bash

      - name: Generate sale.flag schema
        run: cd ./glue/schema && python -m generate_sale_flag_schema
        shell: bash

      - name: Validate Terraform config
        run: terraform validate
        shell: bash

      - name: Apply Terraform changes
        run: terraform apply -auto-approve
        shell: bash
